elements.flash_powder = {
    color: ["#C0C0C0", "#E0E0E0", "#FFFFFF"],
    behavior: behaviors.POWDER,
    category: "powders",
    state: "solid",
    density: 3200,
    desc: "An extremely sensitive, highly reactive silver powder that detonates into intense light and heat upon impact or spark.",
    burn: 100,
    burnTime: 5,
    burnInto: ["plasma", "fire", "smoke", "smoke"],
    tempHigh: 120,
    stateHigh: "fire",
    reactions: {
        "fire": {elem1: "plasma", elem2: "plasma"},
        "spark": {elem1: "plasma", elem2: "plasma"},
        "water": {elem1: "flash_powder", elem2: "steam"}
    }
};

elements.plasma = {
    color: ["#00FFFF", "#FFFFFF", "#0080FF"],
    behavior: behaviors.GAS,
    category: "gases",
    state: "gas",
    density: 100,
    desc: "Superheated matter generated by explosive chemical reactions.",
    temp: 4500,
    tempLow: 800,
    stateLow: "smoke"
};
